### ISSUE TITLE
atom-shell & electron something

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#109]
```js
app.on('window-all-close', function() {
  if (process.platform !== 'darwin') {
    // https://github.com/atom/electron/issues/1731
    //
    // 1. 使用 app.quit() 有时会导致 localStorage 异常, 具体有
    //   - 键值丢失
    //   - 数据错乱 (返回至某一时刻的值, 哎哟, 还带回滚的)
    //
    // 2. 开发过程中, 直接 kill process 也会导致此问题
    //
    // app.quit()
    app.exit()
  }
})
```

**Comment by coderhaoxin** [comment]
* electron 默认 不支持 cookie (可自行开启)
* 打包的坑
  - mac 下 通过 wine 生成 win 的 执行包 (OK), 但在 windows 下打包时, icon 始终无法打包成功

**Comment by coderhaoxin** [comment]
### 已知的问题

* html render bug
  - `textarea` 的 `placeholder` 不会消失 [issue](https://github.com/atom/electron/issues/2581)
  - 其他

* css bug
  - `calc` 等
  - 其他

* localStorage - 持久化bug
  - [issue](https://github.com/atom/electron/issues/1731)

* windows-package `no plan`

* windows-updater [WIP PR](https://github.com/atom/electron/pull/1984)

**Comment by coderhaoxin** [comment]
呼啦啦

**Comment by haoxins** [comment]
呼啦啦
