### ISSUE TITLE
[es7] typed-objects

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#66]
* parse body to typed-objects
* set typed-objects to body

**Comment by coderhaoxin** [comment]
maybe need a new module

* json string -> typed-objects
* typed-objects -> json string
* object -> typed-objects
* typed-objects -> object
* class -> typed-objects

**Comment by haoxins** [comment]
```js
.parse()
.stringify()
.toObject()
.toMap()
```

**Comment by coderhaoxin** [comment]
move this issue to https://github.com/onebook/struct-mapping/issues/1
