### ISSUE TITLE
sass|scss vs cssnext vs myth

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#77]
* [segmentio/myth](https://github.com/segmentio/myth)
* [cssnext/cssnext](https://github.com/cssnext/cssnext)

**Comment by coderhaoxin** [comment]
@reacher-lu 感觉咋样，`cssnext`, `myth` 理念差不多。

**Comment by reacher-lu** [comment]
看我口型

**Comment by coderhaoxin** [comment]
http://oocss.org/spec/css-mixins.html

话说这 `oocss` 到底是啥背景?

**Comment by coderhaoxin** [comment]
如果加上 `mixin`， 那么 `scss` 感觉没啥用处了。

**Comment by coderhaoxin** [comment]
可惜没有 mixin
