### ISSUE TITLE
[develop rule] nodejs & javascript

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#83]
### test

```js
'use strict'

/**
 * 测试文件 与 被测试文件 一一对应
 */

describe('## 某一文件', function() {
  describe('# 某一函数', function() {
    it('case', function() {})
  })
})

/**
 * assert
 */
const assert = require('assert')
const equal = assert.deepEqual

// should
let a, b

// ...

// should
assert(a > b)
assert(a + 10 > b)
equal(a, b)

// not
assert(a === b) // use equal
equal(a > b, true) // use assert

/**
 * 关于断言库
 *   - 基础模块直接 assert
 *   - 业务项目 chai
 *
 * 关于测试框架
 *   - mocha
 *
 * 关于工具库
 *   - http service 测试用 supertest
 */

```

**Comment by coderhaoxin** [comment]
### web 服务文件组织

```
/project
  /template
    index.jade
  /service (或者 /api /view)
  /config
    product.js
    develop.js
  /common
    db.js
  /model
  /route
  /util
    kit.js
  /test
  /data
    init.sh
    init.sql
    table.sql

  app.js
  config.js
  cluster.js

  package.sh
  deploy.sh
```

**Comment by coderhaoxin** [comment]
### log
* log 分级
* 隐藏错误是大忌, 要 log 任何异常, 错误
  - 有些异常可以不用处理, 但也要 log, 便于统计分析等
* info 日志: 具体的用户操作 (下订单等)
  - 某些 bug 会出现在具体用户的具体操作上, 所以, 用户行为相关日志需要记录 (视业务需求而定)

### assert
* assert 一般仅出现在基本模块中, 不出现在业务层 (业务层的 assert 参考 jshttp/http-assert)
* assert 一般仅出现在函数入口处
* assert 一般仅在一个函数中出现一次
* assert 便于 debug, 避免出现 panic

### debug
* 前端 和 后端 不一样, 前端的 debug 应该多一些
  - 无需考虑性能负担
  - 前端环境多样, 异常情况较多
  - 一般在错误处理处需要 debug 信息
* 测试代码中, 关键位置也可以加 debug 信息

**Comment by coderhaoxin** [comment]
### 异常防范
* 合理的 try catch
  - 在有全局 catch 的情况下, 对 edge case 的 except 不要 try catch
* js 内部函数的输入, 输出必定是明确的, 不要容错 (可变参数除外)
  - 容错只会造成 代码冗余 , 隐藏代码错误, 调试困难, 难以排查 bug
* 适当的容错
  - 每次 `xx && xx.oo` 或 `a = a || {}` 等类似代码出现时, 评估一下
  - (接上) 如果防范的情况根本不应该出现 (出现 即为 -> 异常), 此时, 是否更应该抛出异常, 留下日志 ? (不要隐藏错误)

* 当需要的容错措施较多时, try catch

* 对 `接口返回值`, `数据库查询`, `函数返回值` 的检验要 **适度**, **合理**
  - 一般, 接口返回值 **最** 需要容错, 视接口规范程度而定
* 对 **内部函数调用** 的返回值 **不做验证**

```js
/**
 * @return {Object}
 */
function fun1() {
  // ...
}

let obj = fun1()

// 直接
let a = obj.a
// 不要
if (obj) {
  // ...
}
```

* 有时, `return {}` 是个糟主意
  - `findItemById()`, `return {}`, 后续判断不存在 (not exist) 不直接

* 所以, `return` 保持高度一致性
  - `Boolean`: true, false
  - `Number`: 空值: 视业务逻辑而定
  - `String`: 空值: ''
  - `Object`: 空值: `return`
  - `Array`:  空值: `[]`

* 接上 **内部函数调用** 对输入参数 **不做验证**
* 只有业务型的函数会考虑参数容错, 基础性的函数一律不容错

**Comment by coderhaoxin** [comment]
* 容错级别
  - api: 严格校验, 容错 或 400
  - lib: 看情况
  - 内部函数: 不容错, 少用 assert


* 错误处理
  - callback: callback(error)
  - promise: reject(error)
  - generator || sync func: throw error (参见: javascript.md)


### (内部) 第三方数据 (如: api) 的容错处理
* 基本可以假设返回数据的合理性
* 出现错误应该为 500 ??? 即: 不容错, 全局错误捕获处理
  尼玛: 这个必须再磨叽一下下 !!!

**Comment by coderhaoxin** [comment]
* 函数设计
  - 命名: 以 `动词` 开始
  - 对于必填参数进行基本的 assert
  - error 的处理方式 (throw, reject, callback) 必需一致
  - 返回值 (return, resolve, callback) 必需是理想值
  - 何为返回结果是理想值? 即: 返回值类型必须一致, 尤其是空值
     - `非理想值`: 查询特定用户信息,      返回 `null`
     - `理想值`:   查询某一范围商品,      返回 `[]`
     - `理想值`:   判断用户有访问权限,    返回 `false`

  - 返回值 为 空值 时, 必须规范
     - `array`: `[]`
     - `number`: `0`
     - `string`: `''`
     - `object`: `null`, 非 `{}`
     - `boolean`: `false`

  - 有时, 为了方便, 会在函数入口处做统一的基本的容错, 切记: 不要过度容错
  - 通过规范详细的 @param, @return 描述函数, 规范代码
    ```js
    /**
     * @param {number} - userId
     * @param {{skip: number, limit: number}} - options
     * @return {{name: string, age: number}[]}
    */
    ```



```js
/**
 * generate
 */
function * getUserInfo(id, options) {
  assert(typeof id === 'number', 'invalid id');

  // optional params
  options = options || {};

  // do something - http request, database query, some logic

  // 如果出错
  throw error;

  return detail; // detail 是理想值
}

/**
 * callback
 */
function * getUserInfo(id, options, callback) {
  assert(typeof id === 'number', 'invalid id');

  // optional params
  options = options || {};

  // do something - http request, database query, some logic

  // 如果出错
  return callback(error);

  callback(null, detail); // detail 是理想值
}

/**
 * promise
 */
function * getUserInfo(id, options, callback) {
  assert(typeof id === 'number', 'invalid id');

  // optional params
  options = options || {};

  var promise = new Promise(function(resolve, reject) {
    // do something - http request, database query, some logic

    // 如果出错
    reject(error);

    resolve(detail); // detail 是理想值
  });

  return promise;
}

```

**Comment by haoxins** [comment]
### 同一文件内代码组织

* high level -> lower level

```js
function doSomething() {
  // ...
  util()
  // ...
}

function util() {

}
```

* public -> private

```js
exports.some = some

function some() {

}
```

**Comment by haoxins** [comment]
### 不要提升变量声明

### 避免函数内部声明函数

```js
function sumArray(arr) {
  return arr.reduce(function (a, b) {
    return a + b
  }, 0)
}
```

* should:

```js
function sumArray(arr) {
  return arr.reduce(reduceSum, 0)
}

function reduceSum(a, b) {
  return a + b
}
```

但是, 有时也非必要:

```js
function multiplyArray(x) {
  return arr.map((y) => {
    return x * y
  })
}
```

### 后置函数声明

```js
function () {
  // do this
  // do that
  done()

  function done() {

  }
}
```

```js
function () {
  // do this
  // do that
  done()

  return 'something'

  function done() {

  }
}
```
