### ISSUE TITLE
2015-06 pre

### ISSUE THREAD

**Issue by coderhaoxin** [haoxins/mylog#90]
Referer

* [关于前端框架](http://www.cnblogs.com/sskyy/p/4592353.html)

**Comment by coderhaoxin** [comment]
### ES6 module

### Loader

**Comment by coderhaoxin** [comment]
### Web Component

### Polymer

### Angular

### React

**Comment by coderhaoxin** [comment]
### Flux

### Pjax

**Comment by coderhaoxin** [comment]
* 关于 javascript

  - 从 coffee 到 typescript(JS的超集), 再到(strong mode), JS的子集
  - [ES6](https://kangax.github.io/compat-table/es6/)
  - [ES7](http://kangax.github.io/compat-table/es7/)
  - 弱类型, 强类型 [coderhaoxin/typed-objects](https://github.com/coderhaoxin/typed-objects)
  - promise -> async, await

* 关于 web api
  - event & promise & ...
  - import & module & loader & ...
  - xhr & fetch

**Comment by haoxins** [comment]
@coderhaoxin test
